# Generated by Django 4.0.3 on 2023-02-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_auth_tokens_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='userimage/user-icon.png', upload_to='uploads/userimage/'),
        ),
    ]
