# Generated by Django 4.0.3 on 2023-03-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='userimage/user-icon.png', upload_to='userimage/'),
        ),
    ]
