# Generated by Django 4.0.3 on 2023-03-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='local_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
