# Generated by Django 4.0.3 on 2023-03-16 10:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_local_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default=accounts.models.get_default_profile_image, null=True, upload_to='userimage/'),
        ),
    ]
