# Generated by Django 4.0.3 on 2023-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='user-icon.png', null=True, upload_to='userimage/'),
        ),
    ]
