# Generated by Django 4.0.3 on 2023-03-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='links',
            field=models.TextField(null=True),
        ),
    ]
