# Generated by Django 4.2.2 on 2023-07-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_profile_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="links",
            field=models.TextField(
                default={"facebook": "", "instagram": "", "twitter": "", "youtube": ""},
                null=True,
            ),
        ),
    ]
