# Generated by Django 4.0.3 on 2023-01-28 08:35

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=sorl.thumbnail.fields.ImageField(unique=True, upload_to=''),
        ),
    ]
