# Generated by Django 4.0.3 on 2023-01-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='main_img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='exact_place',
            field=models.TextField(default='Nepal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
