# Generated by Django 4.0.3 on 2023-01-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_img_post_main_img_remove_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_img',
            field=models.ImageField(unique=True, upload_to=''),
        ),
    ]
