# Generated by Django 4.0.3 on 2023-02-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_exact_place_post_local_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_img',
            field=models.ImageField(unique=True, upload_to='uploads//'),
        ),
    ]
