# Generated by Django 4.0.3 on 2023-07-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='m_img_url',
            field=models.TextField(default='https://upload.wikimedia.org/wikipedia/commons/0/07/Nepal_logo.svg', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='main_img',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='uploads//'),
        ),
    ]
