# Generated by Django 4.2.2 on 2024-10-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_post_m_img_url_alter_post_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads//'),
        ),
    ]
